// Customer Dashboard Data
export const customerUser = {
  id: "cust-1",
  name: "Rahul Sharma",
  email: "rahul.sharma@email.com",
  phone: "+91 98765 43210",
  avatar: "/indian-professional-man.png",
  addresses: [
    { id: "addr-1", label: "Home", address: "123, MG Road, Koramangala, Bangalore - 560034" },
    { id: "addr-2", label: "Office", address: "456, Brigade Gateway, Malleswaram, Bangalore - 560003" },
  ],
  savedRestaurants: ["rest-1", "rest-3"],
}

export const customerOrders = [
  {
    id: "ORD-001",
    restaurant: "The Spice Room",
    items: ["Butter Chicken", "Garlic Naan (2)", "Dal Makhani"],
    total: 850,
    status: "delivered",
    date: "2024-01-15",
    rating: 4.5,
  },
  {
    id: "ORD-002",
    restaurant: "Pasta Paradise",
    items: ["Margherita Pizza", "Creamy Alfredo Pasta"],
    total: 720,
    status: "preparing",
    date: "2024-01-18",
    rating: null,
  },
  {
    id: "ORD-003",
    restaurant: "Sushi Express",
    items: ["California Roll (8pc)", "Miso Soup", "Edamame"],
    total: 1200,
    status: "on-the-way",
    date: "2024-01-18",
    rating: null,
  },
]

export const customerBookings = [
  {
    id: "BKG-001",
    restaurant: "The Spice Room",
    date: "2024-01-20",
    time: "7:30 PM",
    guests: 4,
    tableType: "Family Table",
    status: "confirmed",
    preOrder: true,
  },
  {
    id: "BKG-002",
    restaurant: "Coastal Delights",
    date: "2024-01-22",
    time: "8:00 PM",
    guests: 2,
    tableType: "Outdoor",
    status: "pending",
    preOrder: false,
  },
  {
    id: "BKG-003",
    restaurant: "Biryani House",
    date: "2024-01-10",
    time: "1:00 PM",
    guests: 6,
    tableType: "Private Room",
    status: "completed",
    preOrder: true,
  },
]

// Restaurant Admin Data
export const restaurantUser = {
  id: "rest-admin-1",
  name: "Priya Nair",
  email: "priya@spiceroom.com",
  role: "Restaurant Manager",
  avatar: "/indian-woman-professional.png",
  restaurant: {
    id: "rest-1",
    name: "The Spice Room",
    cuisine: "North Indian",
    rating: 4.5,
    totalOrders: 1250,
    totalRevenue: 875000,
  },
}

export const restaurantOrders = [
  {
    id: "ORD-101",
    customer: "Rahul S.",
    items: ["Butter Chicken x1", "Garlic Naan x2", "Dal Makhani x1"],
    total: 850,
    status: "pending",
    eta: "12 mins",
    orderTime: "7:15 PM",
    tableNo: "T-5",
  },
  {
    id: "ORD-102",
    customer: "Anita K.",
    items: ["Paneer Tikka x1", "Roti x4", "Raita x1"],
    total: 520,
    status: "preparing",
    eta: "8 mins",
    orderTime: "7:08 PM",
    tableNo: "T-3",
  },
  {
    id: "ORD-103",
    customer: "Vikram M.",
    items: ["Biryani x2", "Kebab Platter x1"],
    total: 980,
    status: "ready",
    eta: "0 mins",
    orderTime: "6:55 PM",
    tableNo: "T-8",
  },
  {
    id: "ORD-104",
    customer: "Sneha P.",
    items: ["Thali Special x1"],
    total: 450,
    status: "served",
    eta: "-",
    orderTime: "6:30 PM",
    tableNo: "T-2",
  },
]

export const restaurantBookings = [
  {
    id: "BKG-101",
    customer: "Rahul Sharma",
    phone: "+91 98765 43210",
    date: "Today",
    time: "7:30 PM",
    guests: 4,
    tableType: "Family Table",
    status: "arriving",
    eta: "5 mins",
    preOrder: true,
  },
  {
    id: "BKG-102",
    customer: "Meera Reddy",
    phone: "+91 87654 32109",
    date: "Today",
    time: "8:00 PM",
    guests: 2,
    tableType: "Couple Table",
    status: "confirmed",
    eta: "25 mins",
    preOrder: false,
  },
  {
    id: "BKG-103",
    customer: "Arjun Singh",
    phone: "+91 76543 21098",
    date: "Today",
    time: "8:30 PM",
    guests: 8,
    tableType: "Private Room",
    status: "confirmed",
    eta: "55 mins",
    preOrder: true,
  },
]

export const restaurantMenuItems = [
  {
    id: "menu-1",
    name: "Butter Chicken",
    category: "Main Course",
    price: 350,
    available: true,
    image: "/butter-chicken.png",
    orders: 245,
  },
  {
    id: "menu-2",
    name: "Paneer Tikka",
    category: "Starters",
    price: 280,
    available: true,
    image: "/paneer-tikka.png",
    orders: 189,
  },
  {
    id: "menu-3",
    name: "Dal Makhani",
    category: "Main Course",
    price: 220,
    available: true,
    image: "/creamy-dal-makhani.png",
    orders: 312,
  },
  {
    id: "menu-4",
    name: "Garlic Naan",
    category: "Breads",
    price: 60,
    available: true,
    image: "/garlic-naan.png",
    orders: 520,
  },
  {
    id: "menu-5",
    name: "Chicken Biryani",
    category: "Rice",
    price: 320,
    available: false,
    image: "/flavorful-chicken-biryani.png",
    orders: 156,
  },
]

export const restaurantTables = [
  { id: "T-1", name: "Table 1", type: "round-2", capacity: 2, x: 50, y: 50, status: "available", currentBooking: null },
  {
    id: "T-2",
    name: "Table 2",
    type: "round-2",
    capacity: 2,
    x: 150,
    y: 50,
    status: "occupied",
    currentBooking: "BKG-102",
  },
  {
    id: "T-3",
    name: "Table 3",
    type: "square-4",
    capacity: 4,
    x: 280,
    y: 50,
    status: "available",
    currentBooking: null,
  },
  {
    id: "T-4",
    name: "Table 4",
    type: "square-4",
    capacity: 4,
    x: 410,
    y: 50,
    status: "reserved",
    currentBooking: "BKG-101",
  },
  { id: "T-5", name: "Table 5", type: "rect-6", capacity: 6, x: 50, y: 180, status: "occupied", currentBooking: null },
  {
    id: "T-6",
    name: "Table 6",
    type: "rect-6",
    capacity: 6,
    x: 220,
    y: 180,
    status: "available",
    currentBooking: null,
  },
  {
    id: "T-7",
    name: "Table 7",
    type: "round-4",
    capacity: 4,
    x: 410,
    y: 180,
    status: "available",
    currentBooking: null,
  },
  {
    id: "T-8",
    name: "Table 8",
    type: "rect-8",
    capacity: 8,
    x: 100,
    y: 320,
    status: "reserved",
    currentBooking: "BKG-103",
  },
  {
    id: "T-9",
    name: "Table 9",
    type: "round-6",
    capacity: 6,
    x: 350,
    y: 320,
    status: "available",
    currentBooking: null,
  },
  {
    id: "T-10",
    name: "Table 10",
    type: "diamond-4",
    capacity: 4,
    x: 480,
    y: 320,
    status: "cleaning",
    currentBooking: null,
  },
  {
    id: "T-11",
    name: "Private Room",
    type: "rect-10",
    capacity: 10,
    x: 100,
    y: 450,
    status: "reserved",
    currentBooking: null,
  },
  {
    id: "T-12",
    name: "Outdoor 1",
    type: "round-4",
    capacity: 4,
    x: 350,
    y: 450,
    status: "available",
    currentBooking: null,
  },
]

export const restaurantReviews = [
  {
    id: "rev-1",
    customer: "Rahul Sharma",
    avatar: "/indian-professional-man.png",
    rating: 5,
    food: 5,
    service: 5,
    ambiance: 4,
    comment: "Amazing butter chicken! Best I've had in Bangalore. Will definitely come back.",
    date: "2024-01-18",
    orderId: "ORD-001",
    reply: null,
  },
  {
    id: "rev-2",
    customer: "Anita Kapoor",
    avatar: null,
    rating: 4,
    food: 4,
    service: 4,
    ambiance: 4,
    comment: "Good food and nice ambiance. Slightly slow service during peak hours.",
    date: "2024-01-17",
    orderId: "ORD-078",
    reply: "Thank you for your feedback! We're working on improving our service speed.",
  },
  {
    id: "rev-3",
    customer: "Vikram Mehta",
    avatar: null,
    rating: 3,
    food: 4,
    service: 2,
    ambiance: 3,
    comment: "Food was good but waited 45 mins despite having a reservation.",
    date: "2024-01-16",
    orderId: "ORD-065",
    reply: null,
  },
  {
    id: "rev-4",
    customer: "Priya Das",
    avatar: null,
    rating: 5,
    food: 5,
    service: 5,
    ambiance: 5,
    comment: "Perfect dining experience! The pre-order feature saved us so much time.",
    date: "2024-01-15",
    orderId: "ORD-052",
    reply: "Thank you so much! We're glad DineOnTime made your experience better!",
  },
]

export const restaurantAnalytics = {
  dailyOrders: [
    { day: "Mon", orders: 45, revenue: 31500 },
    { day: "Tue", orders: 52, revenue: 36400 },
    { day: "Wed", orders: 48, revenue: 33600 },
    { day: "Thu", orders: 61, revenue: 42700 },
    { day: "Fri", orders: 89, revenue: 62300 },
    { day: "Sat", orders: 124, revenue: 86800 },
    { day: "Sun", orders: 98, revenue: 68600 },
  ],
  topItems: [
    { name: "Butter Chicken", orders: 245, revenue: 85750 },
    { name: "Garlic Naan", orders: 520, revenue: 31200 },
    { name: "Dal Makhani", orders: 312, revenue: 68640 },
    { name: "Paneer Tikka", orders: 189, revenue: 52920 },
    { name: "Chicken Biryani", orders: 156, revenue: 49920 },
  ],
  peakHours: [
    { hour: "12PM", orders: 35 },
    { hour: "1PM", orders: 58 },
    { hour: "2PM", orders: 42 },
    { hour: "6PM", orders: 28 },
    { hour: "7PM", orders: 65 },
    { hour: "8PM", orders: 89 },
    { hour: "9PM", orders: 72 },
    { hour: "10PM", orders: 38 },
  ],
  customerMetrics: {
    newCustomers: 128,
    returningCustomers: 312,
    avgOrderValue: 685,
    avgRating: 4.5,
  },
}

export const incomingCustomers = [
  {
    id: "eta-1",
    customer: "Rahul Sharma",
    phone: "+91 98765 43210",
    bookingId: "BKG-101",
    eta: "5 mins",
    etaMinutes: 5,
    distance: "1.2 km",
    guests: 4,
    tableAssigned: "T-4",
    preOrder: true,
    preOrderItems: ["Butter Chicken x2", "Garlic Naan x4", "Dal Makhani x1"],
    preOrderTotal: 1020,
    status: "on-way",
  },
  {
    id: "eta-2",
    customer: "Meera Reddy",
    phone: "+91 87654 32109",
    bookingId: "BKG-102",
    eta: "25 mins",
    etaMinutes: 25,
    distance: "4.5 km",
    guests: 2,
    tableAssigned: "T-2",
    preOrder: false,
    preOrderItems: [],
    preOrderTotal: 0,
    status: "on-way",
  },
  {
    id: "eta-3",
    customer: "Arjun Singh",
    phone: "+91 76543 21098",
    bookingId: "BKG-103",
    eta: "55 mins",
    etaMinutes: 55,
    distance: "12 km",
    guests: 8,
    tableAssigned: "T-8",
    preOrder: true,
    preOrderItems: ["Thali Special x8", "Gulab Jamun x8"],
    preOrderTotal: 4400,
    status: "not-started",
  },
]

// Super Admin Data
export const superAdminUser = {
  id: "admin-1",
  name: "Vikram Patel",
  email: "vikram@dineontime.com",
  role: "Platform Admin",
  avatar: "/indian-man-business-suit.jpg",
}

export const platformStats = {
  totalRestaurants: 524,
  activeUsers: 15420,
  totalOrders: 45230,
  totalRevenue: 12500000,
  pendingApprovals: 12,
  activeComplaints: 8,
}

export const pendingRestaurants = [
  {
    id: "pending-1",
    name: "Taste of Kerala",
    owner: "Arun Menon",
    email: "arun@tasteofkerala.com",
    phone: "+91 98765 11111",
    location: "Indiranagar, Bangalore",
    cuisine: "Kerala",
    appliedDate: "2024-01-16",
    documents: "verified",
  },
  {
    id: "pending-2",
    name: "Dragon Wok",
    owner: "Lin Chen",
    email: "lin@dragonwok.com",
    phone: "+91 98765 22222",
    location: "Whitefield, Bangalore",
    cuisine: "Chinese",
    appliedDate: "2024-01-17",
    documents: "pending",
  },
  {
    id: "pending-3",
    name: "Pizza Roma",
    owner: "Marco D'souza",
    email: "marco@pizzaroma.com",
    phone: "+91 98765 33333",
    location: "JP Nagar, Bangalore",
    cuisine: "Italian",
    appliedDate: "2024-01-18",
    documents: "verified",
  },
]

export const allRestaurants = [
  {
    id: "rest-1",
    name: "The Spice Room",
    owner: "Priya Nair",
    location: "Koramangala, Bangalore",
    cuisine: "North Indian",
    rating: 4.5,
    orders: 1250,
    revenue: 875000,
    status: "active",
    commission: 15,
  },
  {
    id: "rest-2",
    name: "Pasta Paradise",
    owner: "Ravi Kumar",
    location: "Indiranagar, Bangalore",
    cuisine: "Italian",
    rating: 4.3,
    orders: 980,
    revenue: 720000,
    status: "active",
    commission: 15,
  },
  {
    id: "rest-3",
    name: "Sushi Express",
    owner: "Kenji Tanaka",
    location: "MG Road, Bangalore",
    cuisine: "Japanese",
    rating: 4.7,
    orders: 650,
    revenue: 980000,
    status: "active",
    commission: 12,
  },
  {
    id: "rest-4",
    name: "Biryani House",
    owner: "Ahmed Khan",
    location: "Frazer Town, Bangalore",
    cuisine: "Hyderabadi",
    rating: 4.4,
    orders: 1450,
    revenue: 650000,
    status: "active",
    commission: 15,
  },
  {
    id: "rest-5",
    name: "Green Leaf Cafe",
    owner: "Sunita Sharma",
    location: "HSR Layout, Bangalore",
    cuisine: "Healthy",
    rating: 4.1,
    orders: 420,
    revenue: 280000,
    status: "suspended",
    commission: 18,
  },
]

export const platformComplaints = [
  {
    id: "CMP-001",
    type: "Order Issue",
    customer: "Ramesh K.",
    restaurant: "The Spice Room",
    description: "Order arrived cold and late",
    status: "open",
    priority: "high",
    date: "2024-01-18",
  },
  {
    id: "CMP-002",
    type: "Payment Issue",
    customer: "Lakshmi S.",
    restaurant: "Pasta Paradise",
    description: "Double charged for order",
    status: "in-progress",
    priority: "urgent",
    date: "2024-01-17",
  },
  {
    id: "CMP-003",
    type: "Service Quality",
    customer: "Deepak M.",
    restaurant: "Sushi Express",
    description: "Rude staff behavior",
    status: "resolved",
    priority: "medium",
    date: "2024-01-15",
  },
]

export const revenueData = [
  { month: "Aug", revenue: 8500000 },
  { month: "Sep", revenue: 9200000 },
  { month: "Oct", revenue: 10100000 },
  { month: "Nov", revenue: 11300000 },
  { month: "Dec", revenue: 12800000 },
  { month: "Jan", revenue: 12500000 },
]

export const restaurantPayments = [
  {
    id: "PAY-001",
    period: "Jan 1-7, 2024",
    orders: 312,
    grossAmount: 218400,
    commission: 32760,
    netAmount: 185640,
    status: "settled",
    settledDate: "2024-01-10",
  },
  {
    id: "PAY-002",
    period: "Jan 8-14, 2024",
    orders: 345,
    grossAmount: 241500,
    commission: 36225,
    netAmount: 205275,
    status: "settled",
    settledDate: "2024-01-17",
  },
  {
    id: "PAY-003",
    period: "Jan 15-21, 2024",
    orders: 298,
    grossAmount: 208600,
    commission: 31290,
    netAmount: 177310,
    status: "pending",
    settledDate: null,
  },
]
