export const restaurants = [
  {
    id: "1",
    name: "The Spice Room",
    cuisine: "North Indian",
    rating: 4.8,
    reviews: 324,
    priceRange: "$$",
    image: "/upscale-indian-restaurant-interior-with-warm-light.jpg",
    address: "123 MG Road, Bangalore",
    distance: "1.2 km",
    deliveryTime: "25-35 min",
    isOpen: true,
    tags: ["Popular", "Trending"],
    tables: [
      { type: "2-seater", available: 5 },
      { type: "4-seater", available: 3 },
      { type: "6-seater", available: 2 },
    ],
  },
  {
    id: "2",
    name: "Sakura Japanese Kitchen",
    cuisine: "Japanese",
    rating: 4.6,
    reviews: 189,
    priceRange: "$$$",
    image: "/modern-japanese-restaurant-with-sushi-bar.jpg",
    address: "45 Koramangala, Bangalore",
    distance: "2.5 km",
    deliveryTime: "30-40 min",
    isOpen: true,
    tags: ["New"],
    tables: [
      { type: "2-seater", available: 8 },
      { type: "4-seater", available: 4 },
    ],
  },
  {
    id: "3",
    name: "La Piazza",
    cuisine: "Italian",
    rating: 4.7,
    reviews: 256,
    priceRange: "$$",
    image: "/cozy-italian-restaurant-with-brick-walls-and-strin.jpg",
    address: "78 Indiranagar, Bangalore",
    distance: "3.1 km",
    deliveryTime: "35-45 min",
    isOpen: true,
    tags: ["Family Friendly"],
    tables: [
      { type: "2-seater", available: 4 },
      { type: "4-seater", available: 6 },
      { type: "8-seater", available: 1 },
    ],
  },
  {
    id: "4",
    name: "Dragon Palace",
    cuisine: "Chinese",
    rating: 4.5,
    reviews: 412,
    priceRange: "$$",
    image: "/elegant-chinese-restaurant-with-red-lanterns.jpg",
    address: "32 Brigade Road, Bangalore",
    distance: "1.8 km",
    deliveryTime: "25-30 min",
    isOpen: true,
    tags: ["Best Seller"],
    tables: [
      { type: "2-seater", available: 6 },
      { type: "4-seater", available: 5 },
      { type: "Round Table", available: 2 },
    ],
  },
  {
    id: "5",
    name: "The Green Bowl",
    cuisine: "Healthy",
    rating: 4.4,
    reviews: 98,
    priceRange: "$",
    image: "/bright-healthy-restaurant-with-plants-and-natural-.jpg",
    address: "56 HSR Layout, Bangalore",
    distance: "4.2 km",
    deliveryTime: "20-25 min",
    isOpen: false,
    tags: ["Vegan Options"],
    tables: [
      { type: "2-seater", available: 10 },
      { type: "4-seater", available: 4 },
    ],
  },
  {
    id: "6",
    name: "Biryani Blues",
    cuisine: "Hyderabadi",
    rating: 4.9,
    reviews: 567,
    priceRange: "$$",
    image: "/traditional-hyderabadi-restaurant-with-ornate-deco.jpg",
    address: "89 Whitefield, Bangalore",
    distance: "5.5 km",
    deliveryTime: "35-45 min",
    isOpen: true,
    tags: ["Top Rated", "Must Try"],
    tables: [
      { type: "2-seater", available: 3 },
      { type: "4-seater", available: 7 },
      { type: "Family Table", available: 3 },
    ],
  },
]

export const menuItems = [
  {
    id: "m1",
    restaurantId: "1",
    name: "Butter Chicken",
    description: "Tender chicken in a rich, creamy tomato-based sauce with aromatic spices",
    price: 350,
    image: "/butter-chicken-curry-in-bowl.jpg",
    category: "Main Course",
    isVeg: false,
    isPopular: true,
    customizations: ["Extra Gravy", "Less Spicy", "No Onion"],
  },
  {
    id: "m2",
    restaurantId: "1",
    name: "Paneer Tikka",
    description: "Marinated cottage cheese cubes grilled to perfection in tandoor",
    price: 280,
    image: "/paneer-tikka-on-skewer.jpg",
    category: "Starters",
    isVeg: true,
    isPopular: true,
    customizations: ["Extra Mint Chutney", "Well Done"],
  },
  {
    id: "m3",
    restaurantId: "1",
    name: "Dal Makhani",
    description: "Slow-cooked black lentils in a creamy, buttery gravy",
    price: 220,
    image: "/dal-makhani-in-copper-bowl.jpg",
    category: "Main Course",
    isVeg: true,
    isPopular: false,
    customizations: ["Extra Butter", "Less Cream"],
  },
  {
    id: "m4",
    restaurantId: "1",
    name: "Garlic Naan",
    description: "Soft leavened bread topped with garlic and butter",
    price: 60,
    image: "/garlic-naan.png",
    category: "Breads",
    isVeg: true,
    isPopular: true,
    customizations: ["Extra Garlic", "Plain"],
  },
  {
    id: "m5",
    restaurantId: "1",
    name: "Gulab Jamun",
    description: "Soft milk dumplings soaked in rose-flavored sugar syrup",
    price: 120,
    image: "/gulab-jamun-dessert.png",
    category: "Desserts",
    isVeg: true,
    isPopular: true,
    customizations: ["Warm", "With Ice Cream"],
  },
  {
    id: "m6",
    restaurantId: "1",
    name: "Chicken Biryani",
    description: "Fragrant basmati rice layered with spiced chicken and saffron",
    price: 320,
    image: "/chicken-biryani-with-raita.jpg",
    category: "Rice & Biryani",
    isVeg: false,
    isPopular: true,
    customizations: ["Extra Raita", "Less Spicy", "Boneless"],
  },
]

export const cuisineTypes = [
  "All",
  "North Indian",
  "South Indian",
  "Chinese",
  "Italian",
  "Japanese",
  "Mexican",
  "Healthy",
  "Fast Food",
  "Desserts",
]

export const sortOptions = [
  { value: "relevance", label: "Relevance" },
  { value: "rating", label: "Rating: High to Low" },
  { value: "distance", label: "Distance: Nearest" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
]
